#############################################################################
# Makefile for building: luminosus.app/Contents/MacOS/luminosus
# Generated by qmake (3.0) (Qt 5.8.0)
# Project:  ../luminosus_qt/luminosus.pro
# Template: app
# Command: /Users/tim/Qt5.8.0/5.8/ios/bin/qmake -o luminosus.xcodeproj/project.pbxproj ../luminosus_qt/luminosus.pro -spec macx-xcode CONFIG+=release CONFIG+=iphoneos CONFIG+=device
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/tim/Qt5.8.0/5.8/ios/bin/qmake
luminosus.xcodeproj/project.pbxproj: ../luminosus_qt/luminosus.pro ../Qt5.8.0/5.8/ios/mkspecs/macx-ios-clang/qmake.conf ../Qt5.8.0/5.8/ios/mkspecs/features/spec_pre.prf \
		../Qt5.8.0/5.8/ios/mkspecs/qdevice.pri \
		../Qt5.8.0/5.8/ios/mkspecs/features/device_config.prf \
		../Qt5.8.0/5.8/ios/mkspecs/common/unix.conf \
		../Qt5.8.0/5.8/ios/mkspecs/common/mac.conf \
		../Qt5.8.0/5.8/ios/mkspecs/common/uikit.conf \
		../Qt5.8.0/5.8/ios/mkspecs/common/ios.conf \
		../Qt5.8.0/5.8/ios/mkspecs/common/sanitize.conf \
		../Qt5.8.0/5.8/ios/mkspecs/common/gcc-base.conf \
		../Qt5.8.0/5.8/ios/mkspecs/common/gcc-base-mac.conf \
		../Qt5.8.0/5.8/ios/mkspecs/common/clang.conf \
		../Qt5.8.0/5.8/ios/mkspecs/common/clang-mac.conf \
		../Qt5.8.0/5.8/ios/mkspecs/common/ios/clang.conf \
		../Qt5.8.0/5.8/ios/mkspecs/common/ios/qmake.conf \
		../Qt5.8.0/5.8/ios/mkspecs/qconfig.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_core.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_help.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_location.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_network.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qdds.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qico.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qios.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../Qt5.8.0/5.8/ios/mkspecs/features/qt_functions.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/qt_config.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/uikit/qt_config.prf \
		../Qt5.8.0/5.8/ios/mkspecs/macx-ios-clang/qmake.conf \
		../Qt5.8.0/5.8/ios/mkspecs/macx-xcode/qmake.conf \
		../Qt5.8.0/5.8/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt5.8.0/5.8/ios/mkspecs/features/exclusive_builds.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/mac/sdk.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/uikit/sdk.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/toolchain.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/mac/toolchain.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/default_pre.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/mac/default_pre.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/uikit/default_pre.prf \
		../luminosus_qt/deployment.pri \
		../Qt5.8.0/5.8/ios/mkspecs/features/resolve_config.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/uikit/resolve_config.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/default_post.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/mac/default_post.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/uikit/default_post.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/mac/objective_c.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/uikit/bitcode.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/warn_on.prf \
		../Qt5.8.0/5.8/ios/plugins/platforms/libqios.prl \
		../Qt5.8.0/5.8/ios/mkspecs/features/qt.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/uikit/qt.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/resources.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/moc.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/unix/opengl.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/uic.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/unix/thread.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/qmake_use.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/file_copies.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/mac/rez.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/mac/asset_catalogs.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/testcase_targets.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/uikit/testcase_targets.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/exceptions.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/yacc.prf \
		../Qt5.8.0/5.8/ios/mkspecs/features/lex.prf \
		../luminosus_qt/luminosus.pro \
		../Qt5.8.0/5.8/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		../Qt5.8.0/5.8/ios/mkspecs/macx-ios-clang/LaunchScreen.xib \
		../luminosus_qt/qml.qrc \
		../luminosus_qt/images.qrc \
		../luminosus_qt/fonts.qrc \
		../luminosus_qt/qmlBlocks.qrc \
		../luminosus_qt/examples.qrc \
		../Qt5.8.0/5.8/ios/lib/libQt5FontDatabaseSupport.prl \
		../Qt5.8.0/5.8/ios/lib/libQt5GraphicsSupport.prl \
		../Qt5.8.0/5.8/ios/lib/libQt5ClipboardSupport.prl \
		../Qt5.8.0/5.8/ios/lib/libQt5Gui.prl \
		../Qt5.8.0/5.8/ios/lib/libqtharfbuzz.prl \
		../Qt5.8.0/5.8/ios/lib/libQt5Core.prl \
		../Qt5.8.0/5.8/ios/lib/libqtpcre.prl \
		../Qt5.8.0/5.8/ios/lib/libqtfreetype.prl \
		../Qt5.8.0/5.8/ios/lib/libqtlibpng.prl \
		../Qt5.8.0/5.8/ios/lib/libQt5Quick.prl \
		../Qt5.8.0/5.8/ios/lib/libQt5Multimedia.prl \
		../Qt5.8.0/5.8/ios/lib/libQt5Svg.prl \
		../Qt5.8.0/5.8/ios/lib/libQt5Widgets.prl \
		../Qt5.8.0/5.8/ios/lib/libQt5Qml.prl \
		../Qt5.8.0/5.8/ios/lib/libQt5Network.prl \
		../Qt5.8.0/5.8/ios/qml/QtQuick.2/libqtquick2plugin.prl \
		../Qt5.8.0/5.8/ios/qml/QtQuick/Dialogs/libdialogplugin.prl \
		../Qt5.8.0/5.8/ios/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.prl \
		../Qt5.8.0/5.8/ios/qml/Qt/labs/settings/libqmlsettingsplugin.prl \
		../Qt5.8.0/5.8/ios/qml/QtQuick/Dialogs/Private/libdialogsprivateplugin.prl \
		../Qt5.8.0/5.8/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin.prl \
		../Qt5.8.0/5.8/ios/qml/QtQuick/PrivateWidgets/libwidgetsplugin.prl \
		../Qt5.8.0/5.8/ios/qml/QtQuick/Window.2/libwindowplugin.prl \
		../Qt5.8.0/5.8/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl \
		../Qt5.8.0/5.8/ios/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.prl \
		../Qt5.8.0/5.8/ios/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.prl \
		../Qt5.8.0/5.8/ios/plugins/mediaservice/libqavfcamera.prl \
		../Qt5.8.0/5.8/ios/plugins/mediaservice/libqavfmediaplayer.prl \
		../Qt5.8.0/5.8/ios/plugins/mediaservice/libqtmedia_audioengine.prl \
		../Qt5.8.0/5.8/ios/plugins/audio/libqtaudio_coreaudio.prl \
		../Qt5.8.0/5.8/ios/plugins/playlistformats/libqtmultimedia_m3u.prl \
		../Qt5.8.0/5.8/ios/plugins/iconengines/libqsvgicon.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqdds.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqgif.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqicns.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqico.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqjpeg.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqmacjp2.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqsvg.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqtga.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqtiff.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqwbmp.prl \
		../Qt5.8.0/5.8/ios/plugins/imageformats/libqwebp.prl \
		../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_debugger.prl \
		../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_inspector.prl \
		../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_local.prl \
		../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_native.prl \
		../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_profiler.prl \
		../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl \
		../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_server.prl \
		../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_tcp.prl \
		../Qt5.8.0/5.8/ios/plugins/bearer/libqgenericbearer.prl
	$(QMAKE) -o luminosus.xcodeproj/project.pbxproj ../luminosus_qt/luminosus.pro -spec macx-xcode CONFIG+=release CONFIG+=iphoneos CONFIG+=device
../Qt5.8.0/5.8/ios/mkspecs/features/spec_pre.prf:
../Qt5.8.0/5.8/ios/mkspecs/qdevice.pri:
../Qt5.8.0/5.8/ios/mkspecs/features/device_config.prf:
../Qt5.8.0/5.8/ios/mkspecs/common/unix.conf:
../Qt5.8.0/5.8/ios/mkspecs/common/mac.conf:
../Qt5.8.0/5.8/ios/mkspecs/common/uikit.conf:
../Qt5.8.0/5.8/ios/mkspecs/common/ios.conf:
../Qt5.8.0/5.8/ios/mkspecs/common/sanitize.conf:
../Qt5.8.0/5.8/ios/mkspecs/common/gcc-base.conf:
../Qt5.8.0/5.8/ios/mkspecs/common/gcc-base-mac.conf:
../Qt5.8.0/5.8/ios/mkspecs/common/clang.conf:
../Qt5.8.0/5.8/ios/mkspecs/common/clang-mac.conf:
../Qt5.8.0/5.8/ios/mkspecs/common/ios/clang.conf:
../Qt5.8.0/5.8/ios/mkspecs/common/ios/qmake.conf:
../Qt5.8.0/5.8/ios/mkspecs/qconfig.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dcore.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dextras.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dinput.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquick.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3drender.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_concurrent.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_core.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_core_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_gui.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_gui_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_help.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_help_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_location.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_location_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_multimedia.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_network.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_network_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_networkauth.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_nfc.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_opengl.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_positioning.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_printsupport.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qml.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qml_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qmltest.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quick.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quick_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_scxml.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_sensors.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_sql.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_sql_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_svg.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_svg_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_testlib.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_uitools.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_webchannel.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_websockets.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_webview.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_webview_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_widgets.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_xml.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_xml_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_lib_zlib_private.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qdds.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qgif.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qicns.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qico.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qios.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtga.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtiff.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
../Qt5.8.0/5.8/ios/mkspecs/modules/qt_plugin_qwebp.pri:
../Qt5.8.0/5.8/ios/mkspecs/features/qt_functions.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/qt_config.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/uikit/qt_config.prf:
../Qt5.8.0/5.8/ios/mkspecs/macx-ios-clang/qmake.conf:
../Qt5.8.0/5.8/ios/mkspecs/macx-xcode/qmake.conf:
../Qt5.8.0/5.8/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt5.8.0/5.8/ios/mkspecs/features/exclusive_builds.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/mac/sdk.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/uikit/sdk.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/toolchain.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/mac/toolchain.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/default_pre.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/mac/default_pre.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/uikit/default_pre.prf:
../luminosus_qt/deployment.pri:
../Qt5.8.0/5.8/ios/mkspecs/features/resolve_config.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/uikit/resolve_config.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/default_post.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/mac/default_post.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/uikit/default_post.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/mac/objective_c.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/uikit/bitcode.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/warn_on.prf:
../Qt5.8.0/5.8/ios/plugins/platforms/libqios.prl:
../Qt5.8.0/5.8/ios/mkspecs/features/qt.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/uikit/qt.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/resources.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/moc.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/unix/opengl.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/uic.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/unix/thread.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/qmake_use.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/file_copies.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/mac/rez.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/mac/asset_catalogs.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/testcase_targets.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/uikit/testcase_targets.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/exceptions.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/yacc.prf:
../Qt5.8.0/5.8/ios/mkspecs/features/lex.prf:
../luminosus_qt/luminosus.pro:
../Qt5.8.0/5.8/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
../Qt5.8.0/5.8/ios/mkspecs/macx-ios-clang/LaunchScreen.xib:
../luminosus_qt/qml.qrc:
../luminosus_qt/images.qrc:
../luminosus_qt/fonts.qrc:
../luminosus_qt/qmlBlocks.qrc:
../luminosus_qt/examples.qrc:
../Qt5.8.0/5.8/ios/lib/libQt5FontDatabaseSupport.prl:
../Qt5.8.0/5.8/ios/lib/libQt5GraphicsSupport.prl:
../Qt5.8.0/5.8/ios/lib/libQt5ClipboardSupport.prl:
../Qt5.8.0/5.8/ios/lib/libQt5Gui.prl:
../Qt5.8.0/5.8/ios/lib/libqtharfbuzz.prl:
../Qt5.8.0/5.8/ios/lib/libQt5Core.prl:
../Qt5.8.0/5.8/ios/lib/libqtpcre.prl:
../Qt5.8.0/5.8/ios/lib/libqtfreetype.prl:
../Qt5.8.0/5.8/ios/lib/libqtlibpng.prl:
../Qt5.8.0/5.8/ios/lib/libQt5Quick.prl:
../Qt5.8.0/5.8/ios/lib/libQt5Multimedia.prl:
../Qt5.8.0/5.8/ios/lib/libQt5Svg.prl:
../Qt5.8.0/5.8/ios/lib/libQt5Widgets.prl:
../Qt5.8.0/5.8/ios/lib/libQt5Qml.prl:
../Qt5.8.0/5.8/ios/lib/libQt5Network.prl:
../Qt5.8.0/5.8/ios/qml/QtQuick.2/libqtquick2plugin.prl:
../Qt5.8.0/5.8/ios/qml/QtQuick/Dialogs/libdialogplugin.prl:
../Qt5.8.0/5.8/ios/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.prl:
../Qt5.8.0/5.8/ios/qml/Qt/labs/settings/libqmlsettingsplugin.prl:
../Qt5.8.0/5.8/ios/qml/QtQuick/Dialogs/Private/libdialogsprivateplugin.prl:
../Qt5.8.0/5.8/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin.prl:
../Qt5.8.0/5.8/ios/qml/QtQuick/PrivateWidgets/libwidgetsplugin.prl:
../Qt5.8.0/5.8/ios/qml/QtQuick/Window.2/libwindowplugin.prl:
../Qt5.8.0/5.8/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl:
../Qt5.8.0/5.8/ios/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.prl:
../Qt5.8.0/5.8/ios/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.prl:
../Qt5.8.0/5.8/ios/plugins/mediaservice/libqavfcamera.prl:
../Qt5.8.0/5.8/ios/plugins/mediaservice/libqavfmediaplayer.prl:
../Qt5.8.0/5.8/ios/plugins/mediaservice/libqtmedia_audioengine.prl:
../Qt5.8.0/5.8/ios/plugins/audio/libqtaudio_coreaudio.prl:
../Qt5.8.0/5.8/ios/plugins/playlistformats/libqtmultimedia_m3u.prl:
../Qt5.8.0/5.8/ios/plugins/iconengines/libqsvgicon.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqdds.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqgif.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqicns.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqico.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqjpeg.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqmacjp2.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqsvg.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqtga.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqtiff.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqwbmp.prl:
../Qt5.8.0/5.8/ios/plugins/imageformats/libqwebp.prl:
../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_debugger.prl:
../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_inspector.prl:
../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_local.prl:
../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_native.prl:
../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_profiler.prl:
../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl:
../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_server.prl:
../Qt5.8.0/5.8/ios/plugins/qmltooling/libqmldbg_tcp.prl:
../Qt5.8.0/5.8/ios/plugins/bearer/libqgenericbearer.prl:
qmake: FORCE
	@$(QMAKE) -o luminosus.xcodeproj/project.pbxproj ../luminosus_qt/luminosus.pro -spec macx-xcode CONFIG+=release CONFIG+=iphoneos CONFIG+=device

qmake_all: FORCE

